version: '2'
services:
    mybooks-app:
        image: mybooks
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mybooks-postgresql:5432/mybooks
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8084:8084
    mybooks-postgresql:
        extends:
            file: postgresql.yml
            service: mybooks-postgresql
